"""Add order number

Revision ID: 1f96f1c11662
Revises: 74db05a58b78
Create Date: 2026-07-09 20:06:18.211679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f96f1c11662'
down_revision = '74db05a58b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
